import * as fs from 'fs';
import * as path from 'path';
import { WikiEntry, parseFrontmatter } from './types';

export class WikiManager {
  private dir: string;

  constructor(baseDir: string) {
    this.dir = path.join(baseDir, 'wiki');
    fs.mkdirSync(this.dir, { recursive: true });
  }

  private toFrontmatter(entry: WikiEntry): string {
    const front: Record<string, any> = {
      id: entry.id,
      title: entry.title,
      category: entry.category,
      created: entry.created,
      updated: entry.updated,
      related_initiatives: entry.relatedInitiatives,
      tags: entry.tags,
    };
    if (entry.lifecycle) front.lifecycle = entry.lifecycle;
    if (entry.knowledgeType) front.knowledge_type = entry.knowledgeType;
    if (entry.confidence) front.confidence = entry.confidence;
    if (entry.sourceInitiatives && entry.sourceInitiatives.length > 0) front.source_initiatives = entry.sourceInitiatives;
    if (entry.supersedes && entry.supersedes.length > 0) front.supersedes = entry.supersedes;
    if (entry.relatedWiki && entry.relatedWiki.length > 0) front.related_wiki = entry.relatedWiki;
    return `---\n${Object.entries(front).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join('\n')}\n---\n\n`;
  }

  private sanitizeName(name: string): string {
    const base = path.basename(name);
    if (!base || base === '.' || base === '..') {
      throw new Error(`Invalid name: ${name}`);
    }
    return base;
  }

  private generateReferencedBySection(initiativeIds: string[]): string {
    if (initiativeIds.length === 0) return '';
    const lines = initiativeIds.map(id => `- ${id}`);
    return `\n\n## Referenced By\n\n*Auto-generated by mdocs*\n\n${lines.join('\n')}\n`;
  }

  private stripReferencedBySection(content: string): string {
    // Remove the auto-generated Referenced By section (everything from "\n\n## Referenced By" to end)
    const marker = '\n\n## Referenced By\n';
    const idx = content.indexOf(marker);
    if (idx !== -1) {
      return content.slice(0, idx);
    }
    return content;
  }

  private referencedByMarker = '\n\n## Referenced By\n';

  create(entry: WikiEntry): string {
    const category = this.sanitizeName(entry.category);
    const id = this.sanitizeName(entry.id);
    const categoryDir = path.join(this.dir, category);
    fs.mkdirSync(categoryDir, { recursive: true });
    const filePath = path.join(categoryDir, `${id}.md`);
    const referencedBy = this.generateReferencedBySection(entry.relatedInitiatives);
    const content = this.toFrontmatter(entry) + entry.content + referencedBy;
    fs.writeFileSync(filePath, content, 'utf8');
    this.updateIndices();
    return filePath;
  }

  read(category: string, id: string): WikiEntry | null {
    const cat = this.sanitizeName(category);
    const entryId = this.sanitizeName(id);
    const filePath = path.join(this.dir, cat, `${entryId}.md`);
    if (!fs.existsSync(filePath)) return null;
    const content = fs.readFileSync(filePath, 'utf8');
    return this.parseWikiEntry(content);
  }

  private parseWikiEntry(content: string): WikiEntry {
    const front = parseFrontmatter(content);
    if (!Object.keys(front).length) throw new Error('Invalid wiki entry format');

    let body = content.replace(/---\n[\s\S]*?\n---/, '').trim();
    body = this.stripReferencedBySection(body);

    return {
      id: front.id || '',
      title: front.title || '',
      category: front.category || '',
      created: front.created || '',
      updated: front.updated || '',
      relatedInitiatives: Array.isArray(front.related_initiatives) ? front.related_initiatives : [],
      tags: Array.isArray(front.tags) ? front.tags : [],
      content: body,
      lifecycle: front.lifecycle || undefined,
      knowledgeType: front.knowledge_type || undefined,
      confidence: front.confidence || undefined,
      sourceInitiatives: Array.isArray(front.source_initiatives) ? front.source_initiatives : undefined,
      supersedes: Array.isArray(front.supersedes) ? front.supersedes : undefined,
      relatedWiki: Array.isArray(front.related_wiki) ? front.related_wiki : undefined
    };
  }

  private parseRelatedWiki(content: string): string[] {
    const match = content.match(/---\n([\s\S]*?)\n---/);
    if (!match) return [];
    for (const line of match[1].split('\n')) {
      const [key, ...valueParts] = line.split(':');
      if (key?.trim() !== 'related_wiki' || valueParts.length === 0) continue;
      const value = valueParts.join(':').trim();
      try {
        const parsed = JSON.parse(value);
        return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [];
      } catch {
        return [];
      }
    }
    return [];
  }

  private referencedWikiRefs(): Set<string> {
    const refs = new Set<string>();
    const initiativesDir = path.join(path.dirname(this.dir), 'initiatives');
    if (!fs.existsSync(initiativesDir)) return refs;
    const files = fs.readdirSync(initiativesDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
    for (const fileName of files) {
      try {
        const content = fs.readFileSync(path.join(initiativesDir, fileName), 'utf8');
        for (const ref of this.parseRelatedWiki(content)) refs.add(ref);
      } catch {
        // Ignore unreadable initiative files; initiative validation reports them.
      }
    }
    return refs;
  }

  update(category: string, id: string, entry: WikiEntry): string {
    const cat = this.sanitizeName(category);
    const entryId = this.sanitizeName(id);
    const filePath = path.join(this.dir, cat, `${entryId}.md`);

    if (!fs.existsSync(filePath)) {
      throw new Error(`Wiki entry not found: ${cat}/${entryId}`);
    }

    entry.updated = new Date().toISOString().split('T')[0];
    // Strip any existing auto-generated Referenced By section before regenerating
    const cleanContent = this.stripReferencedBySection(entry.content);
    const referencedBy = this.generateReferencedBySection(entry.relatedInitiatives);
    const content = this.toFrontmatter(entry) + cleanContent + referencedBy;
    fs.writeFileSync(filePath, content, 'utf8');
    this.updateIndices();
    return filePath;
  }

  addRelatedInitiative(category: string, id: string, initiativeId: string): string {
    const entry = this.read(category, id);
    if (!entry) {
      throw new Error(`Wiki entry not found: ${category}/${id}`);
    }
    if (!entry.relatedInitiatives.includes(initiativeId)) {
      entry.relatedInitiatives.push(initiativeId);
      entry.updated = new Date().toISOString().split('T')[0];
    }
    return this.update(category, id, entry);
  }

  getReferencedBy(category: string, id: string): string[] {
    const cat = this.sanitizeName(category);
    const entryId = this.sanitizeName(id);
    const wikiRef = `${cat}/${entryId}`;
    const initiativeIds: string[] = [];
    const initiativesDir = path.join(path.dirname(this.dir), 'initiatives');
    if (!fs.existsSync(initiativesDir)) return initiativeIds;

    const files = fs.readdirSync(initiativesDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
    for (const fileName of files) {
      try {
        const content = fs.readFileSync(path.join(initiativesDir, fileName), 'utf8');
        const refs = this.parseRelatedWiki(content);
        if (refs.includes(wikiRef)) {
          // Extract initiative id from frontmatter
          const front = parseFrontmatter(content);
          if (front.id) {
            initiativeIds.push(front.id);
          }
        }
      } catch {
        // Ignore unreadable initiative files
      }
    }
    return initiativeIds;
  }

  private extractWikiRefs(content: string): string[] {
    const refs: string[] = [];
    // Match [[category/id]] wiki links
    const bracketMatches = content.matchAll(/\[\[([^\]]+)\/([^\]]+)\]\]/g);
    for (const match of bracketMatches) {
      refs.push(`${match[1]}/${match[2]}`);
    }
    // Match [text](category/id) markdown links that look like wiki refs
    const linkMatches = content.matchAll(/\[([^\]]*)\]\(([^)]+)\)/g);
    for (const match of linkMatches) {
      const href = match[2];
      // Only consider links that look like category/id (single slash, no protocol)
      if (!href.includes('://') && !href.startsWith('http') && href.split('/').length === 2) {
        const parts = href.split('/');
        if (parts[0] && parts[1]) {
          refs.push(href);
        }
      }
    }
    return [...new Set(refs)]; // deduplicate
  }

  addWikiCrossRef(fromCategory: string, fromId: string, toCategory: string, toId: string): string {
    const fromEntry = this.read(fromCategory, fromId);
    if (!fromEntry) {
      throw new Error(`Wiki entry not found: ${fromCategory}/${fromId}`);
    }
    const toRef = `${toCategory}/${toId}`;
    if (!fromEntry.relatedWiki) {
      fromEntry.relatedWiki = [];
    }
    if (!fromEntry.relatedWiki.includes(toRef)) {
      fromEntry.relatedWiki.push(toRef);
      fromEntry.updated = new Date().toISOString().split('T')[0];
    }
    return this.update(fromCategory, fromId, fromEntry);
  }

  delete(category: string, id: string): void {
    const cat = this.sanitizeName(category);
    const entryId = this.sanitizeName(id);
    const filePath = path.join(this.dir, cat, `${entryId}.md`);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      this.updateIndices();
    }
  }

  list(category?: string): WikiEntry[] {
    const categories = category
      ? [this.sanitizeName(category)]
      : fs.readdirSync(this.dir).filter(f => fs.statSync(path.join(this.dir, f)).isDirectory());

    const entries: WikiEntry[] = [];
    for (const cat of categories) {
      const catDir = path.join(this.dir, cat);
      if (!fs.existsSync(catDir)) continue;
      const files = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      for (const fileName of files) {
        try {
          const entry = this.read(cat, fileName.replace(/\.md$/, ''));
          if (entry) entries.push(entry);
        } catch {
        }
      }
    }
    return entries.sort((a, b) => `${a.category}/${a.id}`.localeCompare(`${b.category}/${b.id}`));
  }

  syncIndices(): string[] {
    this.updateIndices();
    const paths = [path.join(this.dir, 'INDEX.md')];
    const categories = fs.readdirSync(this.dir).filter(f => fs.statSync(path.join(this.dir, f)).isDirectory());
    for (const category of categories) {
      paths.push(path.join(this.dir, category, 'INDEX.md'));
    }
    return paths;
  }

  findRelated(queryTags: string[]): WikiEntry[] {
    const categories = fs.readdirSync(this.dir)
      .filter(f => fs.statSync(path.join(this.dir, f)).isDirectory());

    const results: WikiEntry[] = [];
    for (const category of categories) {
      const catDir = path.join(this.dir, category);
      const files = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      for (const f of files) {
        try {
          const content = fs.readFileSync(path.join(catDir, f), 'utf8');
          const entry = this.parseWikiEntry(content);
          if (entry.tags.some(t => queryTags.includes(t))) {
            results.push(entry);
          }
        } catch {
          // Skip malformed files
        }
      }
    }
    return results;
  }

  stub(category: string, id: string, title?: string, template?: string): { success: boolean; existing?: boolean; filePath: string } {
    const cat = this.sanitizeName(category);
    const entryId = this.sanitizeName(id);
    const categoryDir = path.join(this.dir, cat);
    fs.mkdirSync(categoryDir, { recursive: true });
    const filePath = path.join(categoryDir, `${entryId}.md`);

    if (fs.existsSync(filePath)) {
      return { success: false, existing: true, filePath };
    }

    const date = new Date().toISOString().split('T')[0];
    const stubTitle = title || entryId;
    const stubContent = template || this.defaultStubTemplate(stubTitle, cat, entryId, date);

    fs.writeFileSync(filePath, stubContent, 'utf8');
    this.updateIndices();
    return { success: true, filePath };
  }

  private defaultStubTemplate(title: string, category: string, id: string, date: string): string {
    return `---
id: "${id}"
title: "${title}"
category: "${category}"
created: "${date}"
updated: "${date}"
related_initiatives: []
tags: []
---

## Overview

<!-- Add overview here -->

## Details

<!-- Add details here -->

## References

- Linked from initiative: <!-- initiative ids will be auto-populated -->
`;
  }

  validate(): { valid: boolean; errors: string[]; warnings: string[] } {
    const errors: string[] = [];
    const warnings: string[] = [];
    const referencedWiki = this.referencedWikiRefs();
    const categories = fs.readdirSync(this.dir)
      .filter(f => fs.statSync(path.join(this.dir, f)).isDirectory());

    // Check for broken related_wiki links in initiatives
    const initiativesDir = path.join(path.dirname(this.dir), 'initiatives');
    if (fs.existsSync(initiativesDir)) {
      const initiativeFiles = fs.readdirSync(initiativesDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      for (const fileName of initiativeFiles) {
        try {
          const content = fs.readFileSync(path.join(initiativesDir, fileName), 'utf8');
          for (const ref of this.parseRelatedWiki(content)) {
            const [cat, entryId] = ref.split('/');
            if (!cat || !entryId) {
              errors.push(`Initiative ${fileName} has invalid related_wiki format: ${ref}`);
              continue;
            }
            const wikiFilePath = path.join(this.dir, cat, `${entryId}.md`);
            if (!fs.existsSync(wikiFilePath)) {
              errors.push(`Initiative ${fileName} references missing wiki entry: ${ref}`);
            }
          }
        } catch {
          // Ignore unreadable initiative files
        }
      }
    }

    for (const category of categories) {
      const catDir = path.join(this.dir, category);
      const files = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      for (const fileName of files) {
        const relativeName = `${category}/${fileName}`;
        try {
          const entry = this.parseWikiEntry(fs.readFileSync(path.join(catDir, fileName), 'utf8'));
          if (!entry.id) errors.push(`${relativeName} missing id`);
          if (!entry.title) errors.push(`${relativeName} missing title`);
          if (!entry.category) errors.push(`${relativeName} missing category`);
          if (entry.id && entry.category && !referencedWiki.has(`${entry.category}/${entry.id}`)) {
            warnings.push(`${relativeName} is not referenced by any initiative`);
          }
        } catch (err: any) {
          errors.push(`${relativeName} invalid wiki entry format: ${err.message || String(err)}`);
        }
      }
    }

    return { valid: errors.length === 0, errors, warnings };
  }

  private updateIndices(): void {
    const categories = fs.readdirSync(this.dir)
      .filter(f => fs.statSync(path.join(this.dir, f)).isDirectory());

    // Per-category indices
    for (const category of categories) {
      const catDir = path.join(this.dir, category);
      const files = fs.readdirSync(catDir).filter(f => f.endsWith('.md') && f !== 'INDEX.md');
      const lines = files.map(f => {
        const content = fs.readFileSync(path.join(catDir, f), 'utf8');
        const frontmatterMatch = content.match(/---\n([\s\S]*?)\n---/);
        if (frontmatterMatch) {
          const titleMatch = frontmatterMatch[1].match(/title: "([^"]+)"/);
          if (titleMatch) return `- ${titleMatch[1]}`;
          // Try without quotes
          const unquotedMatch = frontmatterMatch[1].match(/title: (.+)/);
          if (unquotedMatch) return `- ${unquotedMatch[1].trim()}`;
        }
        return `- ${f.replace('.md', '')}`;
      });
      const index = `# ${category}\n\n${lines.join('\n') || 'No entries yet.'}`;
      fs.writeFileSync(path.join(catDir, 'INDEX.md'), index, 'utf8');
    }

    // Root wiki index
    const catLines = categories.map(c => `- [${c}](${c}/INDEX.md)`);
    const rootIndex = `# Wiki\n\n## Categories\n\n${catLines.join('\n')}`;
    fs.writeFileSync(path.join(this.dir, 'INDEX.md'), rootIndex, 'utf8');
  }
}
